spring:

  application:

    name: capstone_microserviceauth
 
  security:

    user:

      name: root

      password: root
 
  datasource:

    url: jdbc:mysql://localhost:3306/happiest

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root

    password: root1234
 
  jpa:

    hibernate:

      ddl-auto: update

    show-sql: true
 
  mail:

    host: smtp.gmail.com

    port: 587

    username: sarathcmurali2000@gmail.com

    password: uxiy qohr nvcx ygxi

    properties:

      mail:

        smtp:

          auth: true

          connectiontimeout: 5000

          timeout: 5000

          writetimeout: 5000

          starttls:

            enable: true
 
server:

  port: 6776
 
eureka:

  client:

    register-with-eureka: true

    fetch-registry: true

    service-url:

      defaultZone: http://localhost:8071/eureka/

 